### ISSUE TITLE
does the api still work? 

### ISSUE THREAD

**Issue by sparten9999** [Risible/Target-Stock-Checker#1]
[https://api.target.com/available_to_promise/v2/53847861/search?key=eb2551e4accc14f38cc42d32fbc2b2ea&nearby=34.052235, -118.243683&inventory_type=stores&multichannel_option=none&field_groups=location_summary&requested_quantity=1&radius=100](url)
using that as an example just gives me a page with the tcin and nothing to parse.

**Comment by sparten9999** [comment]
i would really like to get this to work. am i just messing up the url?

**Comment by Risible** [comment]
Hey, completely forgot I had ever posted this, yes it does still work. I've updated the repo to include the newest version of the file that I'm currently using on my website, risible.io. For most cases, it will return the inventory of the items, however I've found in some cases that Target will just return the TCIN back to you if the item is in high demand and they want to hide the local store inventory.

**Comment by sparten9999** [comment]
seems to be working now thanks. do you have any documentation on the api? like what does "available_to_promise" or "limited_quantity" or others mean

**Comment by Risible** [comment]
available_to_promise, when speaking in terms of local stores, usually pertains to the pickup in store feature. They are only available to promise x amount. Limited Quantity will be what displays on the target website if you were to lookup to see if the item is instock in your store.

The most important thing you want to pay attention to is the onhand_quantity field. This is not a field that Target wants to publicly display on their website. It's also the field that Target went after Brickseek for and had them change to just "In Stock" and "Limited Stock." This field will tell you how many actual units they currently have on hand according to their own inventory systems. Keep in mind that shortage is still a thing, so this number may not be entirely accurate. 

Lastly, there is no documentation for this API, unless you're a target employee that can access the developer.target.com website.
